version: "3.8"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 4000:80
    restart:
      unless-stopped
    depends_on: 
      - redis

  redis:
    image: redis
    ports:
      - 6380:6380
    restart: 
      unless-stopped

networks:
  default:
    driver: bridge
